<a href="https://www.kaggle.com/code/godsonog/analysis-on-epl-since-2000-2001?scriptVersionId=102650305" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Premier League Standings 22 Seasons (2000-2022)

# Context
The Premier League, often referred to as the English Premier League or the EPL (legal name: The Football Association Premier League Limited), is the top level of the English football league system. Contested by 20 clubs, it operates on a system of promotion and relegation with the English Football League (EFL). Seasons run from August to May with each team playing 38 matches (playing all 19 other teams both home and away).[1] Most games are played on Saturday and Sunday afternoons. This data included the premier league standings of the last decade

Analysis
Which teams have the best attacking or defensive record in the last decade ?
Who are the underdogs of the last decade ?

In [15]:
import pandas as pd
epl = pd.read_csv('../input/premier-league-standings-11-seasons-20102021/EPL Standings 2000-2022.csv')
epl = epl.iloc[:,:11]
Best = epl[epl["Season"].between("2011-2012", "2021-2022")]

In [16]:
# ## Which teams have the best attacking or defensive record in the last decade ?
# ### Best Attack
BA_info = Best.sort_values(by="GF", ascending = False).head(50)
BA_info

      Season  Pos               Team  Pld   W   D   L   GF  GA  GD  Pts
340  2017-18    1    Manchester City   38  32   4   2  106  27  79  100
381  2019-20    2    Manchester City   38  26   3   9  102  35  67   81
260  2013-14    1    Manchester City   38  27   5   6  102  37  65   86
261  2013-14    2          Liverpool   38  26   6   6  101  50  51   84
360  2018-19    1    Manchester City   38  32   2   4   95  23  72   98
361  2018-19    2          Liverpool   38  30   7   1   89  22  67   97
321  2016-17    2  Tottenham Hotspur   38  26   8   4   86  26  60   86
240  2012-13    1  Manchester United   38  28   5   5   86  43  43   89
320  2016-17    1            Chelsea   38  30   3   5   85  33  52   93
380  2019-20    1          Liverpool   38  32   3   3   85  33  52   99
343  2017-18    4          Liverpool   38  21  12   5   84  38  46   75
281  2014-15    2    Manchester City   38  24   7   7   83  38  45   79
400  2020-21    1    Manchester City   38  27   5   6   83  32  51   86
322  2016-17    3    Manchester City   38  23   9   6   80  39  41   78
323  2016-17    4          Liverpool   38  22  10   6   78  42  36   76
324  2016-17    5            Arsenal   38  23   6   9   77  44  33   75
242  2012-13    3            Chelsea   38  22   9   7   75  39  36   75
342  2017-18    3  Tottenham Hotspur   38  23   8   7   74  36  38   77
345  2017-18    6            Arsenal   38  19   6  13   74  51  23   63
280  2014-15    1            Chelsea   38  26   9   3   73  32  41   87
401  2020-21    2  Manchester United   38  21  11   6   73  44  29   74
364  2018-19    5            Arsenal   38  21   7  10   73  51  22   70
243  2012-13    4            Arsenal   38  21  10   7   72  37  35   73
282  2014-15    3            Arsenal   38  22   9   7   71  36  35   75
262  2013-14    3            Chelsea   38  25   7   6   71  27  44   82
246  2012-13    7          Liverpool   38  16  13   9   71  43  28   61
303  2015-16    4    Manchester City   38  19   9  10   71  41  30   66
383  2019-20    4            Chelsea   38  20   6  12   69  54  15   66
302  2015-16    3  Tottenham Hotspur   38  19  13   6   69  35  34   70
402  2020-21    3          Liverpool   38  20   9   9   68  42  26   69
300  2015-16    1     Leicester City   38  23  12   3   68  36  32   81
341  2017-18    2  Manchester United   38  25   6   7   68  28  40   81
406  2020-21    7  Tottenham Hotspur   38  18   8  12   68  45  23   62
404  2020-21    5     Leicester City   38  20   6  12   68  50  18   66
263  2013-14    4            Arsenal   38  24   7   7   68  41  27   79
363  2018-19    4  Tottenham Hotspur   38  23   2  13   67  39  28   71
384  2019-20    5     Leicester City   38  18   8  12   67  41  26   62
244  2012-13    5  Tottenham Hotspur   38  21   9   8   66  46  20   72
382  2019-20    3  Manchester United   38  18  12   8   66  36  30   66
241  2012-13    2    Manchester City   38  23   9   6   66  34  32   78
365  2018-19    6  Manchester United   38  19   9  10   65  54  11   66
301  2015-16    2            Arsenal   38  20  11   7   65  36  29   71
306  2015-16    7    West Ham United   38  16  14   8   65  51  14   62
266  2013-14    7  Manchester United   38  19   7  12   64  43  21   64
307  2015-16    8          Liverpool   38  16  12  10   63  50  13   60
362  2018-19    3            Chelsea   38  21   9   8   63  39  24   72
283  2014-15    4  Manchester United   38  20  10   8   62  37  25   70
344  2017-18    5            Chelsea   38  21   7  10   62  38  24   70
408  2020-21    9       Leeds United   38  18   5  15   62  54   8   59
326  2016-17    7            Everton   38  17  10  11   62  44  18   61

In [17]:
BA_info["Team"].value_counts()

Manchester City      9
Liverpool            8
Manchester United    7
Chelsea              7
Arsenal              7
Tottenham Hotspur    6
Leicester City       3
West Ham United      1
Leeds United         1
Everton              1
Name: Team, dtype: int64

In [18]:
# ### Best Defence
BD_info = Best.sort_values(by="GA", ascending= True).head(50)
BD_info

      Season  Pos                     Team  Pld   W   D   L   GF  GA  GD  Pts
361  2018-19    2                Liverpool   38  30   7   1   89  22  67   97
360  2018-19    1          Manchester City   38  32   2   4   95  23  72   98
321  2016-17    2        Tottenham Hotspur   38  26   8   4   86  26  60   86
340  2017-18    1          Manchester City   38  32   4   2  106  27  79  100
262  2013-14    3                  Chelsea   38  25   7   6   71  27  44   82
341  2017-18    2        Manchester United   38  25   6   7   68  28  40   81
325  2016-17    6        Manchester United   38  18  15   5   54  29  25   69
280  2014-15    1                  Chelsea   38  26   9   3   73  32  41   87
400  2020-21    1          Manchester City   38  27   5   6   83  32  51   86
286  2014-15    7              Southampton   38  18   6  14   54  33  21   60
380  2019-20    1                Liverpool   38  32   3   3   85  33  52   99
320  2016-17    1                  Chelsea   38  30   3   5   85  33  52   93
241  2012-13    2          Manchester City   38  23   9   6   66  34  32   78
302  2015-16    3        Tottenham Hotspur   38  19  13   6   69  35  34   70
304  2015-16    5        Manchester United   38  19   9  10   49  35  14   66
381  2019-20    2          Manchester City   38  26   3   9  102  35  67   81
282  2014-15    3                  Arsenal   38  22   9   7   71  36  35   75
403  2020-21    4                  Chelsea   38  19  10   9   58  36  22   67
382  2019-20    3        Manchester United   38  18  12   8   66  36  30   66
300  2015-16    1           Leicester City   38  23  12   3   68  36  32   81
301  2015-16    2                  Arsenal   38  20  11   7   65  36  29   71
342  2017-18    3        Tottenham Hotspur   38  23   8   7   74  36  38   77
283  2014-15    4        Manchester United   38  20  10   8   62  37  25   70
243  2012-13    4                  Arsenal   38  21  10   7   72  37  35   73
260  2013-14    1          Manchester City   38  27   5   6  102  37  65   86
344  2017-18    5                  Chelsea   38  21   7  10   62  38  24   70
343  2017-18    4                Liverpool   38  21  12   5   84  38  46   75
281  2014-15    2          Manchester City   38  24   7   7   83  38  45   79
346  2017-18    7                  Burnley   38  14  12  12   36  39  -3   54
362  2018-19    3                  Chelsea   38  21   9   8   63  39  24   72
388  2019-20    9         Sheffield United   38  14  12  12   39  39   0   54
363  2018-19    4        Tottenham Hotspur   38  23   2  13   67  39  28   71
264  2013-14    5                  Everton   38  21   9   8   61  39  22   72
242  2012-13    3                  Chelsea   38  22   9   7   75  39  36   75
407  2020-21    8                  Arsenal   38  18   7  13   55  39  16   61
322  2016-17    3          Manchester City   38  23   9   6   80  39  41   78
245  2012-13    6                  Everton   38  16  15   7   55  40  15   63
386  2019-20    7  Wolverhampton Wanderers   38  15  14   9   51  40  11   59
303  2015-16    4          Manchester City   38  19   9  10   71  41  30   66
384  2019-20    5           Leicester City   38  18   8  12   67  41  26   62
305  2015-16    6              Southampton   38  18   9  11   59  41  18   63
263  2013-14    4                  Arsenal   38  24   7   7   68  41  27   79
402  2020-21    3                Liverpool   38  20   9   9   68  42  26   69
323  2016-17    4                Liverpool   38  22  10   6   78  42  36   76
246  2012-13    7                Liverpool   38  16  13   9   71  43  28   61
240  2012-13    1        Manchester United   38  28   5   5   86  43  43   89
266  2013-14    7        Manchester United   38  19   7  12   64  43  21   64
324  2016-17    5                  Arsenal   38  23   6   9   77  44  33   75
401  2020-21    2        Manchester United   38  21  11   6   73  44  29   74
326  2016-17    7                  Everton   38  17  10  11   62  44  18   61

In [19]:
BD_info["Team"].value_counts()

Manchester City            9
Manchester United          8
Chelsea                    7
Liverpool                  6
Arsenal                    6
Tottenham Hotspur          4
Everton                    3
Southampton                2
Leicester City             2
Burnley                    1
Sheffield United           1
Wolverhampton Wanderers    1
Name: Team, dtype: int64

In [20]:
# ### Team with Most Wins
Most_wins = epl.loc[(epl['Pos'] == 1)]
Most_wins.head(10)

      Season  Pos               Team  Pld   W   D  L   GF  GA  GD  Pts
0    2000-01    1  Manchester United   38  24   8  6   79  31  48   80
20   2001-02    1            Arsenal   38  26   9  3   79  36  43   87
40   2002-03    1  Manchester United   38  25   8  5   74  34  40   83
60   2003-04    1            Arsenal   38  26  12  0   73  26  47   90
80   2004-05    1            Chelsea   38  29   8  1   72  15  57   95
100  2005-06    1            Chelsea   38  29   4  5   72  22  50   91
120  2006-07    1  Manchester United   38  28   5  5   83  27  56   89
140  2007-08    1  Manchester United   38  27   6  5   80  22  58   87
160  2008-09    1  Manchester United   38  28   6  4   68  24  44   90
180  2009-10    1            Chelsea   38  27   5  6  103  32  71   86

In [21]:
Most_wins["Team"].value_counts()

Manchester United    7
Manchester City      6
Chelsea              5
Arsenal              2
Leicester City       1
Liverpool            1
Name: Team, dtype: int64

In [22]:
# ### How many points does it usually take to qualify for Europe ?
Europe = epl.iloc[:,2:].groupby("Team").mean().astype(int).sort_values(by = "Pts", ascending=False)
Europe.head(6)

                   Pld   W  D   L  GF  GA  GD  Pts
Team
Manchester United   38  23  8   6  71  35  35   77
Chelsea             38  22  8   7  69  34  35   75
Arsenal             38  21  8   7  70  39  31   72
Liverpool           38  21  9   7  68  36  32   72
Manchester City     38  20  7  10  70  40  30   68
Tottenham Hotspur   38  17  8  11  60  45  14   62

# # Approximately 62 points is needed to qualify for Europe from EPL

# Teams with Most Points since 2000-2001 Season

In [23]:
epl.iloc[:,2:].groupby("Team").sum().sort_values(by = "Pts", ascending = False)

                         Pld    W    D    L    GF    GA   GD   Pts
Team
Manchester United        836  507  177  152  1562   782  780  1698
Chelsea                  836  492  189  155  1538   757  781  1665
Arsenal                  836  470  193  173  1561   876  685  1603
Liverpool                836  464  199  173  1516   808  708  1591
Manchester City          798  428  156  214  1478   846  632  1440
Tottenham Hotspur        836  393  191  252  1323  1011  312  1370
Everton                  836  321  228  287  1102  1059   43  1191
Newcastle United         760  260  193  307   943  1100 -157   973
West Ham United          722  238  181  303   908  1060 -152   895
Aston Villa              722  225  210  287   866  1009 -143   885
Southampton              570  181  161  228   698   803 -105   704
Fulham                   570  162  154  254   631   831 -200   640
Leicester City           418  150  104  164   583   592   -9   554
Blackburn Rovers         418  140  110  168   518   592  -74   530
Sunderland               532  127  139  266   520   795 -275   520
Bolton Wanderers         418  132  110  176   495   613 -118   506
West Bromwich Albion     494  117  139  238   510   772 -262   490
Stoke City               380  116  109  155   398   525 -127   457
Crystal Palace           380  115   92  173   428   545 -117   437
Middlesbrough            380  107  111  162   414   503  -89   432
Wolverhampton Wanderers  304   90   78  136   328   462 -134   348
Wigan Athletic           304   85   76  143   316   482 -166   331
Charlton Athletic        266   85   70  111   301   386  -85   325
Burnley                  304   83   76  145   300   455 -155   325
Swansea City             266   82   66  118   306   383  -77   312
Leeds United             228   87   50   91   319   349  -30   311
Birmingham City          266   73   82  111   273   360  -87   301
Portsmouth               266   79   65  122   292   380  -88   293
Watford                  266   67   60  139   275   441 -166   261
Norwich City             266   56   66  144   251   489 -238   234
Bournemouth              190   56   43   91   241   330  -89   211
Brighton & Hove Albion   190   48   65   77   190   258  -68   209
Hull City                190   41   48  101   181   323 -142   171
Reading                  114   32   23   59   136   186  -50   119
Sheffield United         114   31   22   61    91   157  -66   115
Ipswich Town              76   29   15   32    98   106   -8   102
Queens Park Rangers      114   22   26   66   115   199  -84    92
Derby County             114   19   26   69    90   211 -121    83
Cardiff City              76   17   13   46    66   143  -77    64
Huddersfield Town         76   12   17   47    50   134  -84    53
Brentford                 38   13    7   18    48    56   -8    46
Blackpool                 38   10    9   19    55    78  -23    39
Coventry City             38    8   10   20    36    63  -27    34
Bradford City             38    5   11   22    30    70  -40    26